#!/usr/bin/python3
import argparse
import logging

import dikta
import console

log_levels = {
    'CRITICAL': logging.CRITICAL,
    'ERROR': logging.ERROR,
    'WARNING': logging.WARNING,
    'INFO': logging.INFO,
    'DEBUG': logging.DEBUG
}

ap = argparse.ArgumentParser(description =
    'Interactive "Do I Know It Already" quiz')
ap.add_argument('json_file', type = argparse.FileType('r'),
    help = 'Quiz in JSON format', metavar = 'quiz.json')
ap.add_argument('--loglevel', dest = 'log_level', default = 'WARNING', type = str,
    choices = log_levels.keys(), help = 'Logging verbosity')

group = ap.add_mutually_exclusive_group()
group.add_argument('--list', '-l', dest = 'list_chapters', action = 'store_true',
    help = 'List chapters in quiz and exit')
group.add_argument('--number', '-n', dest = 'number', type = int, metavar = 'N',
    help = 'Only run the chapter with this number')
group.add_argument('--title', '-t', dest = 'title', type = str,
    help = 'Only run the chapter with this title')

args = ap.parse_args()

logging.basicConfig(level = args.log_level)

logging.debug('Loading from "%s"' % args.json_file.name)
quiz = dikta.Quiz(args.json_file, number = args.number, title = args.title)
logging.info('Loaded quiz "%s"' % quiz)

console = console.Console(quiz)
if args.list_chapters:
    console.list_chapters()
else:
    console.run_quiz()
    console.show_mistakes()
    console.show_score()
